name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install PyInstaller
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py

      # Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: my-executable
          path: dist/main.exe
