name: Build and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install PyInstaller
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          
      # Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name bibliographie-zonage main.py
          
      # Zip the main.exe file
      - name: Zip main.exe
        run: |
          zip -j ./dist/bibliographie-zonage.zip ./dist/bibliographie-zonage.exe
      
      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v-${{ github.sha }}"
          release_name: "Release v-1-0-${{ github.run_number }}"
          draft: false
          prerelease: false

      # Upload zipped executable to the release
      - name: Upload executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/bibliographie-zonage.zip
          asset_name: bibliographie-zonage.zip
          asset_content_type: application/zip
