name: Build and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install PyInstaller
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Install Requirements
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          
      # Build the executable
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --icon favicon.ico --name v-1-1-${{ github.run_number }}-bibliographie-zonage main.py
      
      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v-${{ github.sha }}"
          release_name: "Release v-1-1-${{ github.run_number }}"
          draft: false
          prerelease: false

      # Upload zipped executable to the release
      - name: Upload executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/v-1-1-${{ github.run_number }}-bibliographie-zonage.exe
          asset_name: v-1-1-${{ github.run_number }}-bibliographie-zonage.exe
          asset_content_type: application/octet-stream
